modify ...

diff --git a/mybashrc b/mybashrc
--- a/mybashrc
+++ b/mybashrc
@@ -169,7 +169,7 @@ function fm-realpath
 	local tool=realpath
 	which ${tool} > /dev/null
 	if [ $? -ne 0  ];then echo "ERROR:${tool} no found!!";return 2;fi
-	for path in $@
+	for path in $*
 	do
 		local linux_path=$(${tool} ${path})
 		if [ x"${linux_path}" != "x"  ]
@@ -177,7 +177,7 @@ function fm-realpath
 			echo "linux   --- ${linux_path}"
 		fi
 	done
-	for path in $@
+	for path in $*
 	do
 		local linux_path=$(${tool} ${path})
 		if [ x"${linux_path}" != "x"  ]
@@ -198,26 +198,35 @@ function fm-find
 
 function fm-time_zone_update
 {
-	which ntpdate > /dev/null
+	local app=ntpdate
+	local zonefile=/usr/share/zoneinfo/Asia/Shanghai
+	local target_file=/etc/localtime 
+
+	which ${app} > /dev/null
 	if [ $? -ne 0 ]
 	then
-		echo "ERROR:ntpdate not found"
-		echo "please install ntpdate"
-		echo "sudo apt install ntpdate"
+		echo "ERROR:${FUNCNAME},${app} not found"
+		echo "please install ${app}"
+		echo "sudo apt install ${app}"
 		return 1
 	fi
-	local time_server_list="ntp.api.bz"
+	#copy zonefile
+	if [ ! -f ${zonefile} ];then echo "ERROR:${FUNCNAME},${zonefile} not exist!";return 2;fi
+
+	cp -vf ${zonefile} ${target_file}
+
+	#update time from servers
+	local time_server_array=("ntp.ntsc.ac.cn" "ntp1.aliyun.com" "ntp.fudan.edu.cn")
+	for server in $(echo ${time_server_array[*]})
+	do
+		echo "try to connecting time server:${server}"
+		ntpdate -u  ${server}
+		if [ $? -eq 0 ]
+		then
+			break
+		fi
+	done
 	
-	ntpdate -u  ntp.api.bz
-	local zonefile=/usr/share/zoneinfo/Asia/Shanghai
-	if [ ! -f ${zoneinfo} ]
-	then
-		echo "ERROR:${zoneinfo} not exist!"
-		return 2
-	fi
-
-	cp -v ${zoneinfo} /etc/localtime 
-
 	return 0
 }
 
@@ -229,8 +238,8 @@ function fm-download_whole_website
 	
 	if [ $# -lt 1 ];then echo "ERROR:paramter missing!!";echo "$FUNCNAME URL";return 2;fi
 	
-	echo "${tool} -r -p -np -k $@"
-	${tool} -r -p -np -k $@
+	echo "${tool} -r -p -np -k $*"
+	${tool} -r -p -np -k $*
 
 	return 0
 }
