modify and add new file

diff --git a/bash_function_lib/bash_for_work b/bash_function_lib/bash_for_work
--- a/bash_function_lib/bash_for_work
+++ b/bash_function_lib/bash_for_work
@@ -142,6 +142,27 @@ function fm-wifi_qr_code
 	return 0
 }
 
+function fm-convert_url_to_qrcode
+{
+	local app=qrencode
+	local default_opt="-o  - -t UTF8 -m 2"
+
+	if [ $# -lt 1 ]
+	then
+		echo "ERROR:para wrong!!"
+		echo "$FUNCNAME  URL"
+		return 1
+	fi
+	#check app
+	which ${app} > /dev/null
+	if [ $? -ne 0 ];then echo "${app} not exist";echo "please install it first";echo "apt install ${app}";return 2;fi
+	
+	local qrcode_string=$*
+	echo "URL:${qrcode_string}"
+	qrencode ${default_opt} ${qrcode_string}
+	
+	return 0
+}
 
 function fm-fjk_sign_tool
 {
