fix bug

diff --git a/bash_function_lib/media_office_tools b/bash_function_lib/media_office_tools
--- a/bash_function_lib/media_office_tools
+++ b/bash_function_lib/media_office_tools
@@ -178,13 +178,30 @@ function fm-ffmpeg_videofile_stream_push_2my_mediaserver
 function fm-ffmpeg_camera_video_stream_save_2file
 {
 	local push_tool=ffmpeg
+	local check_tool=v4l2-ctl
 	local device=/dev/video
 	local file=output.mp4
+	local resol="480x320"
 	if [ $# -ne 2 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]
 	then
 		echo "ERROR:parameter wrong"
-		echo "$FUNCNAME dev filename"
-		echo "e.g:$FUNCNAME /dev/video0 output.mp4"
+		echo "$FUNCNAME  dev  resolution  filename"
+		echo "e.g:$FUNCNAME /dev/video0  480x320  output.mp4"
+		echo "屏幕分辨率(resolution):"
+		which ${check_tool} > /dev/null
+		if [ $? -eq 0 ]
+		then
+			${check_tool} --list-formats-ext | grep -w "Size:" | awk '{print"resolution: "$3}'
+		else
+			echo "${check_tool} not found!!"
+			echo "please install first:apt install  v4l-utils"
+			echo "320x240   --常见于较早的移动电话和小型设备。"
+			echo "480x320   --常见于早期智能手机和某些小型平板电脑。"
+			echo "800x480   --常见于某些低成本智能手机和平板电脑。"
+			echo "1024x600  --常见于某些小型平板电脑和便携式设备。"
+			echp "1280x720  --高清（HD）分辨率，也称为 720p。"
+			echo "1280x800  --常见于较小的平板电脑和便携式设备。"
+		fi
 		return 1
 	fi
 	which ${push_tool} > /dev/null
@@ -195,18 +212,25 @@ function fm-ffmpeg_camera_video_stream_save_2file
 		return 2
 	fi
 	device=$1
-	file=$2
+	resol=$2
+	file=$3
 	if [ ! -e ${device} ];then echo "device:${} not found!!";return 3;fi
-
-	echo "${push_tool} -f v4l2 -i ${device} -c:v libx264 -preset veryfast -tune zerolatency ${file}"
-	${push_tool} -f v4l2 -i ${device} -c:v libx264 -preset veryfast -tune zerolatency ${file}
-
+	if [ 1 -gt 2 ]
+	then
+		#echo "${push_tool} -f v4l2 -i ${device} -c:v libx264 -preset veryfast -tune zerolatency ${file}"
+		#${push_tool} -f v4l2 -i ${device} -c:v libx264 -preset veryfast -tune zerolatency ${file}
+	else
+		echo "${push_tool} -f v4l2 -s ${resol} -i ${device} ${file}"
+		${push_tool} -f v4l2 -s ${resol} -i ${device} ${file}
+	fi
+	
 	return 0
 }
 function fm-ffmpeg_camera_video_stream_push_2mpvplayer
 {
 	local push_tool=ffmpeg
 	local player=mpv
+	local check_tool=v4l2-ctl
 	local device=/dev/video
 	local resol="480x320"
 
@@ -216,15 +240,20 @@ function fm-ffmpeg_camera_video_stream_push_2mpvplayer
 		echo "$FUNCNAME  dev  resolution"
 		echo "e.g:$FUNCNAME  /dev/video0   480x320"
 	    echo "屏幕分辨率(resolution):"
-		echo "320x240   --常见于较早的移动电话和小型设备。"
-    	echo "480x320   --常见于早期智能手机和某些小型平板电脑。"
-    	echo "800x480   --常见于某些低成本智能手机和平板电脑。"
-    	echo "1024x600  --常见于某些小型平板电脑和便携式设备。"
-		echp "1280x720  --高清（HD）分辨率，也称为 720p。"
-    	echo "1280x800  --常见于较小的平板电脑和便携式设备。"
-		echo "1366x768  --广泛用于笔记本电脑和小型显示器的分辨率。"
-		echo "1600x900  --常见于较大的笔记本电脑和中等尺寸显示器的分辨率。"
-		echo "2560x1440 --2K 分辨率，也称为 Quad HD（QHD）或 1440p。"
+		which ${check_tool} > /dev/null
+		if [ $? -eq 0 ]
+		then
+			${check_tool} --list-formats-ext | grep -w "Size:" | awk '{print"resolution: "$3}'
+		else
+			echo "${check_tool} not found!!"
+			echo "please install first:apt install  v4l-utils"
+			echo "320x240   --常见于较早的移动电话和小型设备。"
+			echo "480x320   --常见于早期智能手机和某些小型平板电脑。"
+			echo "800x480   --常见于某些低成本智能手机和平板电脑。"
+			echo "1024x600  --常见于某些小型平板电脑和便携式设备。"
+			echp "1280x720  --高清（HD）分辨率，也称为 720p。"
+			echo "1280x800  --常见于较小的平板电脑和便携式设备。"
+		fi
 		return 1
 	fi
 	which ${push_tool} > /dev/null
@@ -244,10 +273,14 @@ function fm-ffmpeg_camera_video_stream_push_2mpvplayer
 	device=$1
 	resol=$2
 	if [ ! -e ${device} ];then echo "device:${} not found!!";return 4;fi
-
-	echo "${push_tool} -f v4l2 -s ${resol} -i ${device} -c:v libx264 -preset ultrafast -tune zerolatency -f mpegts - | ${player} -"
-	${push_tool} -f v4l2 -s ${resol} -i ${device} -c:v libx264 -preset ultrafast -tune zerolatency -f mpegts - | mpv -
-
+	if [ x"$SSH_CLIENT" = x ]
+	then
+		echo "${push_tool} -f v4l2 -s ${resol} -i ${device} -c:v libx264 -preset ultrafast -tune zerolatency -f mpegts - | ${player} -"
+		${push_tool} -f v4l2 -s ${resol} -i ${device} -c:v libx264 -preset ultrafast -tune zerolatency -f mpegts - | mpv -
+	else
+		echo "${push_tool} -f v4l2 -s ${resol} -i ${device} -c:v libx264 -preset ultrafast -tune zerolatency -f mpegts - | DISPLAY=:0 ${player} -"
+		${push_tool} -f v4l2 -s ${resol} -i ${device} -c:v libx264 -preset ultrafast -tune zerolatency -f mpegts - | DISPLAY=:0 mpv -
+	fi
 	return 0
 }
 function fm-ffmpeg_camera_video_stream_push_2rtmpserver
