add pirture convert function

diff --git a/bash_function_lib/media_office_tools b/bash_function_lib/media_office_tools
--- a/bash_function_lib/media_office_tools
+++ b/bash_function_lib/media_office_tools
@@ -177,3 +177,55 @@ function fm-video_stream_push_by_ffmpeg_to_mymedia_server
 
 	return 0
 }
+function fm-picture_convert_quality
+{
+	local app=convert
+	local arg_default="-quality"
+
+	if [ $# -ne 3 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]
+	then
+		echo "SYNOPSIS:"
+		echo "$FUNCNAME  input  output  quality"
+		echo "e.g.$FUNCNAME  mypic.jpg  newmyjpg.jpg  80"
+		return 1
+	fi
+	local input=$1
+	local output=$2
+	local qual=$3
+
+	which ${app} > /dev/null
+	if [ $? -ne 0 ];then echo "${app} not found!";echo "apt install imagemagick";return 1;fi
+
+	${app}   ${input}  ${arg_default} ${qual}  ${output}
+	
+	return 0
+}
+function fm-picture_convert_resize
+{
+	local app=convert
+	local arg_default="-resize"
+
+	if [ $# -ne 3 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]
+	then
+		echo "SYNOPSIS:"
+		echo "$FUNCNAME  input  output  resize"
+		echo "e.g.$FUNCNAME  mypic.jpg  newmyjpg.jpg  800x600"
+		echo "resize format: "
+		echo "800   --只指定宽度，而不指定高度,高度会根据原始图像的纵横比自动调整。" 
+		echo "x600  --只指定高度，而不指定宽度,宽度会根据原始图像的纵横比自动调整。"
+		echo "800x600 | 1024x1024 --指定宽度和高度。"
+		echo "50% --使用百分比值来相对于原始图像的尺寸进行调整,50% 表示将图像调整为原始尺寸的一半。"
+		echo "1024x1024>  --使用 > 符号来指定图像的最长边的大小,同时保持纵横比。"
+		return 1
+	fi
+	local input=$1
+	local output=$2
+	local resize=$3
+	if [ ! -f ${input} ];then echo "file:${input} not exist";return 2;fi
+	which ${app} > /dev/null
+	if [ $? -ne 0 ];then echo "${app} not found!";echo "apt install imagemagick";return 3;fi
+
+	${app}   ${input}  ${arg_default} ${resize}  ${output}
+	
+	return 0
+}
