monify

diff --git a/bash_function_lib/media_office_tools b/bash_function_lib/media_office_tools
--- a/bash_function_lib/media_office_tools
+++ b/bash_function_lib/media_office_tools
@@ -29,7 +29,7 @@ function fm-picture_viewer
 function fm-video_player
 {
 	local app=mpv
-	local default_opt="--fs"
+	local default_opt=
 
 	if [ $# -ne 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]
 	then
@@ -49,7 +49,7 @@ function fm-video_player
 		if [ "x${opt}" = "x"  ];then opt="N";fi
 		if [ "x${opt}" = "xy"  ] || [ "x${opt}" = "xY"  ] || [ "x${opt}" = "xyes"  ] || [ "x${opt}" = "xYES"  ]
 		then
-			DISPLAY=:0 $app ${default_opt} "$*"
+			DISPLAY=:0 $app ${default_opt} --fs "$*"
 		fi
 	fi
 	return 0
@@ -81,6 +81,58 @@ function fm-video_mult_player
 			DISPLAY=:0 $app ${default_opt} "$*"
 		fi
 	fi
+	return 0
+}
+
+#Linux Sound volume control
+function fm-linux_sound_volume_control
+{
+	local app=alsamixer
+	local default_opt=
+	if [ "$1" = "-h" ] || [ "$1" = "--help" ]
+	then
+		echo "CN:"
+		echo "" 
+		return 1
+	fi
+	which ${app} > /dev/null
+	if [ $? -ne 0 ];then echo ¨ERROR:${FUNCNAME},${app} not exist!¨;return 2;fi;
+
+	${app}
+	return 0
+}
+function fm-linux_brightness_control
+{
+	local app=xrandr
+	local default_opt=
+	which ${app} > /dev/null
+	if [ $? -ne 0 ];then echo ¨ERROR:${FUNCNAME},${app} not exist!¨;return 2;fi;
+	
+	if [ $# -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]
+	then
+		echo "CN:"
+		echo "$FUNCNAME  monitor  brightness(0-1)" 
+		echo "$FUNCNAME  HDMI-2  0.5"
+		${app} -q | grep -w connected
+		return 1
+	fi
+	local monitor=$1
+	local brightness=$2
+	local  monitor_name=""
+	#check 
+	local monitor_list=$(${app} -q | grep -w connected | awk '{print$1}')
+	for name in ${monitor_list}
+	do
+		if [ ${name} = ${monitor} ]
+		then
+			monitor_name=${name}
+		fi
+	done
+	if [ "x${monitor_name}" = "x" ];then echo "monitor name not found!";return 3;fi
+
+	echo "${app} --output ${monitor_name} --brightness ${brightness}"
+	${app} --output ${monitor_name} --brightness ${brightness}
+
 	return 0
 }
 
