fix bug

diff --git a/bash_function_lib/media_office_tools b/bash_function_lib/media_office_tools
--- a/bash_function_lib/media_office_tools
+++ b/bash_function_lib/media_office_tools
@@ -286,14 +286,31 @@ function fm-ffmpeg_camera_video_stream_push_2mpvplayer
 function fm-ffmpeg_camera_video_stream_push_2rtmpserver
 {
 	local push_tool=ffmpeg
+	local check_tool=v4l2-ctl
 	local server_ip=localhost
 	local server_port=1935
 	local device=/dev/video0
-	if [ $# -lt 3 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]
+	local resol="480x320"
+	if [ $# -lt 4 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]
 	then
 		echo "ERROR:parameter wrong"
-		echo "$FUNCNAME dev IP  port"
-		echo "e.g:$FUNCNAME /dev/video0 116.62.103.60 1935"
+		echo "$FUNCNAME dev resolution IP  port"
+		echo "e.g:$FUNCNAME /dev/video0 1366x768 116.62.103.60 1935"
+		echo "屏幕分辨率(resolution):"
+		which ${check_tool} > /dev/null
+		if [ $? -eq 0 ]
+		then
+			${check_tool} --list-formats-ext | grep -w "Size:" | awk '{print"resolution: "$3}'
+		else
+			echo "${check_tool} not found!!"
+			echo "please install first:apt install  v4l-utils"
+			echo "320x240   --常见于较早的移动电话和小型设备。"
+			echo "480x320   --常见于早期智能手机和某些小型平板电脑。"
+			echo "800x480   --常见于某些低成本智能手机和平板电脑。"
+			echo "1024x600  --常见于某些小型平板电脑和便携式设备。"
+			echp "1280x720  --高清（HD）分辨率，也称为 720p。"
+			echo "1280x800  --常见于较小的平板电脑和便携式设备。"
+		fi
 		return 1
 	fi
 	which ${push_tool} > /dev/null
@@ -304,8 +321,9 @@ function fm-ffmpeg_camera_video_stream_push_2rtmpserver
 		return 2
 	fi
 	device=$1
-	server_ip=$2
-	server_port=$3
+	resol=$2
+	server_ip=$3
+	server_port=$4
 	if [ ! -e ${device} ];then echo "device:${device} not found!!";return 3;fi
 	if ! expr "${server_port}" : '^[0-9]\+$' >/dev/null
 	then
@@ -313,10 +331,14 @@ function fm-ffmpeg_camera_video_stream_push_2rtmpserver
 		echo "$FUNCNAME  loop_times  IP port  video_file_lsit"
 		return 3
 	fi	
-	
-	echo "${push_tool} -f v4l2 -i ${device} -c:v libx264 -preset veryfast -tune zerolatency -f flv rtmp://${server_ip}:${server_port}/live/movie1234"
-	${push_tool} -f v4l2 -i ${device} -c:v libx264 -preset veryfast -tune zerolatency -f flv rtmp://${server_ip}:${server_port}/live/movie1234
-
+	if false
+	then
+		echo "${push_tool} -f v4l2 -i ${device} -c:v libx264 -preset veryfast -tune zerolatency -f flv rtmp://${server_ip}:${server_port}/live/movie1234"
+		${push_tool} -f v4l2 -i ${device} -c:v libx264 -preset veryfast -tune zerolatency -f flv rtmp://${server_ip}:${server_port}/live/movie1234
+	else
+		echo "${push_tool} -f v4l2 -i ${device} -c:v libx264 -preset veryfast -tune zerolatency -f flv rtmp://${server_ip}:${server_port}/live/movie1234"
+		${push_tool} -f v4l2 -s ${resol} -i ${device} -c:v libx264 -preset veryfast -tune zerolatency -f flv rtmp://${server_ip}:${server_port}/live/movie1234
+	fi
 	return 0
 }
 function fm-ffmpeg_screen_record_save_2file
