modify files

diff --git a/bash_function_lib/media_office_tools b/bash_function_lib/media_office_tools
--- a/bash_function_lib/media_office_tools
+++ b/bash_function_lib/media_office_tools
@@ -18,10 +18,64 @@ function fm-movie_player
 	local app=mpv
 	#local default_opt=¨--player-operation-mode=pseudo-gui¨
 	local default_opt=
-	
+
+	if [ "$1" = "-h" ] || [ "$1" = "--help" ]
+	then
+		echo "$FUNCNAME  a.mp4"
+		echo "$FUNCNAME  rtmp://your-streaming-server:port/live/your-stream-key" 
+		return 1
+	fi
 	which ${app} > /dev/null
 	if [ $? -ne 0 ];then echo ¨ERROR:${FUNCNAME},${app} not exist!¨;return 1;fi;
 
 	$app ${default_opt} $*
+	return 0
+}
+
+function fm-movie_stream_push_by_ffmpeg
+{
+	local push_tool=ffmpeg
+
+	local server_ip=116.62.103.60
+	local server_port=1935
+
+	if [ $# -lt 2 ]
+	then
+		echo "ERROR:parameter wrong"
+		echo "$FUNCNAME  loop_times  video_file_lsit"
+		echo "e.g:$FUNCNAME 10 1.mp4 2.flv ..."
+		return 1
+	fi
+	which ${push_tool} > /dev/null
+	if [ $? -ne 0 ]
+	then
+		echo "ERROR:${push_tool} not found,please install it first"
+		echo "apt install ${push_tool}"
+		return 2
+	fi
+	local loop_times=$1
+	if ! expr "${loop_times}" : '^[0-9]\+$' >/dev/null
+	then
+		echo "first para is not number"
+		echo "$FUNCNAME  loop_times  video_file_lsit"
+		return 3
+	fi	
+	shift 1
+	while [ ${loop_times} -gt 0 ]
+	do
+		for file in "$@"
+		do
+			echo "${push_tool} -re -i "$file" -c copy -f flv rtmp://${server_ip}:${server_port}/live/movie1234"
+			${push_tool} -re -i "$file" -c copy -f flv rtmp://${server_ip}:${server_port}/live/movie1234
+		done
+		loop_times=$(expr ${loop_times} - 1)
+	done
+
+#	if [ $# -eq 1 ]
+#	then
+#		echo "${push_tool} -re -stream_loop -10 -i "$1" -c copy -f flv rtmp://${server_ip}:${server_port}/live/movie1234"
+#		#${push_tool} -re -stream_loop -10 -i "$1" -c copy -f flv rtmp://${server_ip}:${server_port}/live/movie1234
+#	fi
+#	
 	return 0
 }
