add new help file

diff --git a/scripts/file_operate_tools b/scripts/file_operate_tools
--- a/scripts/file_operate_tools
+++ b/scripts/file_operate_tools
@@ -25,14 +25,71 @@ function fm-pdf_crack_passwd
 	return 0
 }
 
-function fm-pdf_tk
+function fm-pdf_split
 {
 	local app=pdftk
 	local default_opt=
+	#check parameter
+    if [ $# -ne 1 ] || [ $1 = "-h" ] || [ $1 = "--help" ]
+    then
+        echo "DESCRIPTION:"
+        echo "SYNOPSIS:"
+        echo "         ${FUNCNAME}  src_file  page_num1-page_num2  outfile_name"
+        return 1
+    fi	
 	which ${app} > /dev/null
 	if [ $? -ne 0 ];then echo ¨ERROR:${FUNCNAME},${app} not exist!¨;return 1;fi;
 
 	$app ${default_opt} $*
+	return 0
+}
+
+function fm-pdf_merge
+{
+	local app=pdftk
+	local default_opt=
+
+	#check parameter
+    if [ $# -ne 3 ] || [ $1 = "-h" ] || [ $1 = "--help" ]
+    then
+        echo "DESCRIPTION:"
+        echo "SYNOPSIS:"
+        echo "         ${FUNCNAME}  src_file  page_num1-page_num2  outfile_name"
+		echo "example: ${FUNCNAME}  file.pdf  2-20  out.pdf"
+        return 1
+    fi
+
+
+	which ${app} > /dev/null
+	if [ $? -ne 0 ];then echo ¨ERROR:${FUNCNAME},${app} not exist!¨;return 1;fi;
+
+	$app ${default_opt} $*
+	return 0
+}
+
+function fm-pdf_extract
+{
+	local app=pdftk
+	local default_opt=
+	#check parameter
+    if [ $# -ne 3 ] || [ $1 = "-h" ] || [ $1 = "--help" ]
+    then
+        echo "DESCRIPTION:"
+        echo "SYNOPSIS:"
+        echo "         ${FUNCNAME}  src_file  page_num1-page_num2  outfile_name"
+		echo "example: ${FUNCNAME}  file.pdf  2-20  out.pdf"
+        return 1
+    fi
+	local src_pdf_file=$1
+	local extract_range=$2
+	local outfile_name=$3
+	if [ ! -f ${src_pdf_file} ];then echo "ERROR:file:${src_pdf_file} not exist";return 2;fi
+	
+	which ${app} > /dev/null
+	if [ $? -ne 0 ];then echo ¨ERROR:${FUNCNAME},${app} not exist!¨;return 1;fi;
+	#example:pdftk a.pdf cat 1-end output b.pdf
+	$app ${src_pdf_file}  cat ${extract_range} output ${outfile_name}
+
 	return 0
 }
 
@@ -117,9 +174,4 @@ function fm-rm_overwrite
 	echo "total erase file counts:${total_file_num}"
 	return 0
 }
-
-
-
-
-
 
